name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pwd
        docker --version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}

    - name: Copy files to the test website with the AWS CLI
      run: |
        export AWS_ROLE=dnx-labs2-admin
        export AWS_ACCOUNT_ID=158947203889
        export AWS_DEFAULT_REGION=ap-southeast-2
        env | grep AWS
        aws s3 ls