name: OnApply
on:
  workflow_dispatch:
    inputs:
      action:
        description: list s3
        default: dev
        required: true
jobs:
  deploy:
    name: Deploy To Production
    runs-on: ubuntu-latest
    steps:
      - name: Execute in Production
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Execute list S3
        if: github.event.inputs.action == 'prod' || github.event.inputs.action == 'all'
        run: |
          export AWS_ROLE=dnx-labs2-admin
          export AWS_ACCOUNT_ID=158947203889
          export WORKSPACE=labs2-PROD
          env | grep WORK
          aws s3 ls

      - name: Execute ls
        if: github.event.inputs.action == 'dev' || github.event.inputs.action == 'all'
        run: |
          export AWS_ROLE=dnx-labs2-admin
          export AWS_ACCOUNT_ID=158947203889
          export WORKSPACE=labs2-DEV
          env | grep WORK
          ls -lha